# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: Bits and Pieces on Programming 
description: Programming Blog 
author:
  name: Lucius Chia 
  email: cww9989@gmail.com 
  github: cww0909 
  twitter: 
  pinterest: 
  linkedin: 
  bio: Discoveries, Notes, Reminders, Cheat Sheets etc 
  email_md5: fe97aaa61147977be0929931a5524636 

rss_path: feed
categories_path: categories
about_path: about 
tags_path: tags
profile_pic_path: assets/media/blog_profile.jpg

BASE_PATH: http://cww0909.github.io

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
